### ISSUE TITLE
Unchecking tag in 'Add Tags' dialog doesn't remove tag when hitting Save.

### ISSUE THREAD

**Issue by puregallery** [puregallery/Pure-Gallery-Support#10]

**Comment by puregallery** [comment]
This is by design frankly. If you prefer this option, that means that the 'Remove Tags' option will become obsolete and I should delete that. Will you be fine with that?

**Comment by puregallery** [comment]
@Nostang3 Don't use the "+" icon on the toolbar to add tags to your collection...it is currently replacing old tags with the selected new tags instead of adding them to the old ones.

**Comment by Nostang3** [comment]
@puregallery Good to know. I usually only use the bottom option to add tags because it's easier to hit with my thumb.

**Comment by Nostang3** [comment]
PG now removes the tag when unselected in the Change Tags option. 

@puregallery Do you want to keep this open until you fix the above mentioned issue or do you want to create a new issue for that for more clear tracking?

**Comment by puregallery** [comment]
Lets close this and track it on the other one.
