### ISSUE TITLE
Mass Tagging Mode

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#17]
A Tag Mode for mass tagging. Idea would be like opening up a viewer of the image and have small list of tags(if tagged) overlayed over top of the photo in a corner, then when you tap the photo brings up the tag dialog so you can add/remove tags(In this instance you could show the tags that already tagged checked in the list since you're only dealing with one photo.), and you can swipe left or right to go to the next picture. You could have it prompt you when you enter Tag Mode if you specifically want to tag untagged photos or all in case you want to quickly run through all your photos again and make sure they are all tagged properly. Or maybe even include an option to use Tag Mode on a specific tag you have already created.

**Comment by puregallery** [comment]
>Idea would be like opening up a viewer of the image and have small list of tags(if tagged) overlayed over top of the photo in a corner

This is what I currently addressed in the new tag mode. The centered media's tags are displayed in a horizontal list under the "Current tags" header. You can swipe through all the media items if you need to check the info on all the selected/displayed items.
>when you tap the photo brings up the tag dialog so you can add/remove tags(In this instance you could show the tags that already tagged checked in the list since you're only dealing with one photo.), and you can swipe left or right to go to the next picture

This functionality can be accessed through the "Add tag", "Remove tags" buttons at the bottom of the screen. You can also change the media's favorite status using the icon there. You can also view details of the media. When you scroll through all media files here, their status will be updated below them appropriately. Do you have something else on your mind regarding this? Opening media files in full screen to do all this will end up being very confusing for most users frankly.

**Comment by Nostang3** [comment]
The way you implemented is great for a small selection of similar photos but you can't do the whole album of unique photos because what ever you tag to one gets tagged to all selected photos. I was hoping for a mode to where you could tag your whole album more efficiently. 

I think you have a great foundation for a mass tag mode. It would be similar to what you have but if you tweaked it for a Mass Tag mode then you could:

- Have no photo selection necessary whole album is included, maybe filter by untagged/tagged/all.
- Swipe left or right and bring up the next or previous photo in the album or filtered selection. (like how you swipe for Tinder profiles)
- Apply tags to centered photo only so you don't apply a dog tag to a photo of a cat.
- A way to copy tags of one photo, swipe right, then apply it to another photo. I think this is important because this may add unnecessary extra tags momentarily but removing that extra tag would be quicker than having to reapply all the other tags that do belong and the ui touches. 

Because generally, most of my photos are going to be different enough that I wouldn't include them in a selection for the current tag mode and have to tag them individually. Being in a mass tag mode I could just swipe to the next photo and be quickly tagging again, saving a a lot of ui touches. 

I hope I explained it well enough. If you need me to be more verbose or give you an exact example, I can.

**Comment by puregallery** [comment]
How many things here are still necessary in your opinion? I believe we have all the things here except the copying tags from one photo to other.

**Comment by Nostang3** [comment]
In this case? Currently if I wanted to tag all phone is my library, I have to select one, move all the way to the end of the album and long press to select all the photos then enter tag mode. It would be nice if there was a way to enter a mass tag mode where the whole album is selected but only the visible photo gets tagged and I can just swipe right to the next image. An easy one step option instead of a 4 step. Maybe even include the copy tags to another photo available in this section so you an swipe back to an earlier photo, copy, then swipe back to the one you want and 'paste' the tags. 

This is a shoot for the sky wish. It doesn't need to be in your release version.

**Comment by puregallery** [comment]
I'm trying to identify the missing pieces so that I can keep track of what needs to be implemented.

>but only the visible photo gets tagged and I can just swipe right to the next image

This is already possible in the 'tag view'. The 'Change tags' button does exactly this.
>It would be nice if there was a way to enter a mass tag mode where the whole album is selected

This needs to be implemented...and is simple enough. I'm thinking of giving this option thru the three dots menu in the Album View.
>Maybe even include the copy tags to another photo available in this section so you an swipe back to an earlier photo, copy, then swipe back to the one you want and 'paste' the tags.

This will be a tricky part as in how to implement it...and will be delayed a bit.
