### ISSUE TITLE
When filtering by tags, have the option for 'AND' and 'OR'. 

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#18]
When filtering by tags, have the option for 'AND' and 'OR'. Currently when selecting multiple tags it will show all photos that have any of the tags. For me personally, I need to be able to only show photos that have all the tags attached to a photo. For example, currently when filtering for tagged photos, I select tags: lions, tigers, and bears. This will bring up a photo with just a lion, a photo with just a tiger, and a photo with just a bear, and a photo with a lion, tiger, and a bear. I'd like an 'AND' option for when I only want the photo that has the lion, tiger, and bear in it and not the other three individual photos.

**Comment by Nostang3** [comment]
Currently on the latest version, I don't see the option to toggle per your instructions:

> When you open the filter dialog from an album view or timeline, there should be a toggle/switch under the "tags" section...and the text next to it will update reflecting what you select.

I wonder if this is caused because I have so many tags my tag window takes up the entire screen.

**Comment by Nostang3** [comment]
This feature works as expected. 

I don't know if you want me to create a new issue or just add onto this one but it would be nice if the toggle would remember it's position from one session to another. Not necessary but would be a nice touch.

**Comment by puregallery** [comment]
I'll leave this open util I address this issue too

**Comment by puregallery** [comment]
If I were to implement this, I want the UI to be able to indicate when any album or 'tag album' is filtered. To do this, I am changing the filter icon's color to the primary color in that theme - blue in the 'white-blue', green in the 'white-green' and I'm stuck at the black theme because the primary color in that theme is white, and so are the icon colors by default. Do you use black theme more often? If so, what would be a good color to set on the icon there? How do you feel if I use a completely new color for every theme uniformly? like red on all themes?

**Comment by Nostang3** [comment]
I generally try to use dark/black themes on any app that allows it and on PG I'm using the black theme. I think a uniform color can work. Red stands out and would easily let someone know that the album is filtered. If you didn't want to go that route, yellow is a good color opposite black.

**Comment by puregallery** [comment]
I'll go with red for now...let's tweak the color later on.

**Comment by Nostang3** [comment]
PG now shows a red filter icon(in the black theme) when items are filtered. However if you long press a image and then immediately back out the red icon will return to white and doesn't correctly maintain it's correlation with currently filtered media. 

1. Make a filter selection.
2. Notice red icon
3. Long press photo to select it
4. Press back button on soft keys
5. Notice icon return to white.

Also, when I mentioning keeping the toggle between sessions, I was referring too the ANY/ALL toggle and not the filter selection. Although I do think keeping the filtered selected between sessions is a great feature. This is probably my fault again for not describing my request properly. I apologize.

**Comment by puregallery** [comment]
No worries. Fixed the icon now.

**Comment by Nostang3** [comment]
PG now correctly keeps the state of the color of the icon after dismissing photo selection.
