### ISSUE TITLE
Tags View isn't refreshing after sorting

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#20]
If you go into Tags View and sort by alphabetical, switching between Ascending and Descending only seems to work once. You have switch to Albums and back to Tags before the view will refresh. Only seems to affect Alphabetical sorting that I can see. Albums, seems to sort and refresh as expected.

**Comment by puregallery** [comment]
I don't see this issue happening for me. Can you please double-check and confirm it for me?

**Comment by Nostang3** [comment]
Double checked and it is happening on my phone. 

Steps from a fresh instance of PG:
1. Open PG
2. Three Line Menu
3. Tags
4. Sort Menu
5. It's saved to Alphabetical so I choose Descending then apply and view refreshes.
6. Sort Menu again
7. Ascending then Apply but view doesn't refresh.

**Comment by puregallery** [comment]
In step 2, do you mean go to 'tags' using the left navigation drawer?

**Comment by Nostang3** [comment]
Yes, The Three Line Menu(What I call it) opens the left hand drawer.

**Comment by puregallery** [comment]
Got confused with the three dot menu...my bad.

**Comment by Nostang3** [comment]
It's all good. Everyone has their own terms.

**Comment by Nostang3** [comment]
PG now correctly refreshes the view when changing between selections. Specifically the Ascending/Descending issue described in this thread.
