### ISSUE TITLE
Images in Tag Mode aren't fully displayed

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#23]
Most noticeable is when you are looking at a landscape photo. The sides are severely cut off, limiting what you can see of the photo and what you need to tag. Portrait photos aren't as bad but the tops and bottoms can be cut off as well. Fully viewing the photo would be best for tagging purposes. 

Also, you could take this opportunity to add in options for the photo to Fit or Fill the screen while tagging. Maybe even add a pinch to zoom and move the photo around. Sometimes, I find myself having to back out of tag mode to go into image viewer mode to see the whole picture or need to zoom in on something. Having to back out causes problems when you're filtering by untagged as it immediately removes the photo from the filter view.

**Comment by puregallery** [comment]
The images need to be somehow scaled down based on the available width(70% screen width) there. I will scale down the height in such cases and lets revisit this after I push that change.
If I do this, you will get to view the whole image without being cropped.
By the way, I'm caught up in my other projects' deadlines and I won't get to spend enough time on this for a few weeks. I will do weekly releases until then.

**Comment by Nostang3** [comment]
Is there any reason why it can't fill the entire view? 

If you have to scale the image down based on height because you can't use the whole middle section, then allowing to zoom would be much appreciated for the big landscape images.

Also, you say your caught up in your projects but then also say you won't be able to spend time on this project. Did you mean that you aren't caught up on your projects? Either way is fine, I'm still working on tagging my collection. Release when you can, I know this is a passion project and you have a life to live. Don't feel rushed in anyway by me.

**Comment by puregallery** [comment]
Ah, sorry for the grammatical error I guess...what I meant was that deadlines for a couple of my other projects are coming up, and I need to concentrate on them right now.

I don't know if adding zoom functionality here is worth the effort...I am thinking of implementing instagram's style of opening image - like a full screen popup on long press here....are you aware of that? Will that help you? I just don't prefer repetitive features throughout the app...Each screen should have a unique style :D

**Comment by Nostang3** [comment]
I get what your saying, yeah, if you could long press on an image and have it open up like instagram that would nice.

**Comment by Nostang3** [comment]
PG now shows the full width of a landscaped image. 

Would you mind explaining the reason why you don't use the full width of the screen? It seems like wasted space to me, but I wonder if it's not some coding reason so I'm curious.

**Comment by puregallery** [comment]
I wanted some sense of scrolling indicator in the horizontal list...not the usual way, but something different. And the way I have it - it serves as an indicator when you see images on either side.
Anyway, implemented a scroll view indicator similar to the instagram one. Pushing it today

**Comment by Nostang3** [comment]
PG now displays the full image when tagging, and it's glorious. The new scroll indicator is very nice.
