### ISSUE TITLE
Ability to edit tags after they have been created.

### ISSUE THREAD

**Issue by puregallery** [puregallery/Pure-Gallery-Support#3]

**Comment by Nostang3** [comment]
How does this exactly work? Does it just change the tag in the app? I assume it's not retroactively changing tags already written to files?

**Comment by puregallery** [comment]
It will change the tags written to files as well...it will usually take time if you are attempting to modify content on SdCard...else, it is quite fast.

**Comment by Nostang3** [comment]
This was able to change an already existing tag to something different and update the files.
