### ISSUE TITLE
Implement Zoomable video

### ISSUE THREAD

**Issue by puregallery** [puregallery/Pure-Gallery-Support#30]

**Comment by Nostang3** [comment]
PG exoplayer now allows for zoom. Tested working.

**Comment by puregallery** [comment]
Pending:
1. Add an option to chose the default player.
2. Add the option to settings page.

**Comment by Nostang3** [comment]
I was going to mention the default options. This also reminded me to add some issues. Now I just need to remember what they were. Lol.

**Comment by puregallery** [comment]
No worries...I do have a couple of outstanding issues and that is the reason I marked that feature beta(in a beta app, smh)...
Anyway, the issues:
 1. Can't hide the controls properly.
 2. While zooming, the view doesn't resize the height properly and as a result, the focus point gets lost. 

Turns out zooming a video is wayy different than zooming an image. I have a few ideas regarding this and need to test them out.

**Comment by Nostang3** [comment]
Yeah, the controls was one of the issues I remember having. Just have to remember the other one.

**Comment by Nostang3** [comment]
The controls are now hideable with a screen tap. 

Zoomable player seems to reset to video proper height when un-zooming. And the focus point seems to be on point.
