### ISSUE TITLE
Clearing Tag Filter after file deletion doesn't refresh view

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#32]
So if you go into Album and filter your view, find a photo(in my case the first one) then delete it when you try to clear the tag filter, the view doesn't refresh. If you exit album view and come back in, the view refreshes.

**Comment by Nostang3** [comment]
When I deleted a tagged photo while filtered, it doesn't seem to handle the deletion properly yet. 

I have 4 photos in an album. The 1st and 3rd files are tagged. The 2nd and 4th aren't. I filtered the view to only show the 1st and 3rd tagged photos. I then deleted the 3rd tagged photo. It is removed from tagged view. When I clear the filtered view, the 3rd photo still shows up in view. When clicking on the since deleted 3rd photo it will open up the 4th photo. Leaving the folder and going back in refreshed the view. Tried the reverse with untagged photos, same results. 

I tried this with two photos previously, both tagged, and the photo stayed in view after deletion but clicking on it it tried to open the file, then i saw the tag icon disappear, then PG crashed. I opted for more files to test and the above is the result. 

I then deleted the 2nd and 3rd left over files as I was done testing this, then I tried to long press the remaining 1st file to remove it's tag I created for testing and it crashed PG. I sent feedback, hopefully you got it.

**Comment by puregallery** [comment]
I'm pretty sure the items are moved successfully...just not reported right in the UI. Sorry about that...will fix today

**Comment by puregallery** [comment]
Jeez... this bug is lurking around for a long time...thanks for bringing it to my attention!
The items are deleted/moved properly...but the list is not giving up the item right away when it is filtered.

**Comment by Nostang3** [comment]
I was able to filter, then delete multiple or single files and have the album view refresh. I was also able to view the correct photo I clicked on. Tag filter was able to be cleared and could view the photo I selected in an unfiltered view.
