### ISSUE TITLE
Ability to have an album(s) placed at the top of album view despite sorting

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#33]
This would be an option when clicking in the three dot menu on the album in Album view that which checked out make sure the album stayed at the top of the list despite sorting options. Maybe a favorite option. This would keep frequented albums at the top of the list.

**Comment by puregallery** [comment]
I do that to the album with name "Camera" already...Once I give out such an option, how do you want the app to handle this option set on multiple albums? Or should only one album be able to hold such an option at any time?

**Comment by Nostang3** [comment]
I figure that if you set multiple items to 'favorite' then once they are at the top they can either follow the sorting already set on the album or maybe just have them in alphabetical order.

**Comment by Nostang3** [comment]
I am able to pin folders to the top of the view despite sorting.
