### ISSUE TITLE
Abillity to choose Album cover for a given album.

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#34]
Could be an option when viewing a picture or long pressing on one, to have an option to set as album cover.

**Comment by Nostang3** [comment]
Some things to note. After the 'ok' option in the dialog to select the cover photo, it will disappear but the photo will still be selected. Would it be better for it to be de-selected after?

**Comment by puregallery** [comment]
I thought I'd let the behavior be the same as with the details option.

**Comment by Nostang3** [comment]
My thought process is that when selecting an album cover, you're only going to do that once in a sitting, maybe twice if you happen to scroll and find a better option. So in most cases I feel like you're going to set it and then be done. If the second case happens where you scroll and find another you'll have to uncheck that option, if you didn't already, before you can select a new photo. 

With the details behavior, I can see that making sense because after you view the details you get to choose if you want to delete a photo or not, maybe move it, etc.

**Comment by puregallery** [comment]
sounds good...will remove.

**Comment by Nostang3** [comment]
PG now deselects the picture after it is chosen as album cover.
