### ISSUE TITLE
PureGallery Album shows grey image of non-existent file

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#35]
When clicking on said 'photo' I get an error toast:

> Failed to load resource
> There were 3 causes: 
> java.io.FileNotFoundException(/storage/emulated/0/PureGallery/1520377968270.png (No such file or directory))
> java.io.FileNotFoundException(No such file or directory)
> java.io.FileNotFoundException(No such file or directory) call GlideException#logRootCauses(String) for more detail. 

I can not delete the 'file'. Running a media scan does not update PG to let it know it's not there. I checked in Root Explorer and there is no file present. 

I could theoretically 'create' a file with that naming convention in that folder and then most likely delete it but I will wait for your advice before proceeding.

**Comment by puregallery** [comment]
Did you long press the file and attempt to delete it from PG?
Btw, I'm not getting automatic notifications for issues created here...need to check the notification settings. Until then, can you assign the issues to me so that I can get notified right away?

**Comment by Nostang3** [comment]
I did. It will exit out of the Album and then a toast appears saying: "No media to display here."

Sure, I will assign them to you.

**Comment by Nostang3** [comment]
The bug seems to spreading. Now my screenshots folder shows a album cover of a photo that used to be in there, but if you open the folder it just has grey images that can't be open and show the same message as above when trying to delete. There is a couple other folders as well doing it.

**Comment by puregallery** [comment]
I need to be able to reproduce this...
>photo that used to be in there

How did you delete this picture? from another app?  or from PG itself?

**Comment by puregallery** [comment]
Ok. I'm close to pushing an update...i'll fix this too and push it late today or early tomorrow.

**Comment by Nostang3** [comment]
PG now handles photo deletion/file moved by another app correctly.
