### ISSUE TITLE
Top Bar doesn't refresh after photo deletion

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#37]
When deleting a photo that is tagged, after deletion the top bar will still display "1 Item selected" even though the photo is gone. You have to hit the back button to remove the "selection".

**Comment by puregallery** [comment]
Ah, sorry about that...didn't have any items to delete on my device at the time...so, didn't test this completely. Will fix today.

**Comment by Nostang3** [comment]
Top bar correctly refreshes after a photo is deleted. I am also able to view the photo I selected after deletion.
