### ISSUE TITLE
PG doesn't recognize new photos without media scan

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#40]
I've noticed that when new photos are added to folder on the device that PG doesn't see the change. It will only see the change in folder that currently appear in the app currently and only after a manual refresh. If I want now non empty folders to show up, I have to enter the settings and do a media scan. Other gallery apps seem to be able to detect new additions on the fly without media scans. Is there some hybrid method where it can ping the folders and detect changes quickly?

Example:

Say I have 4 folder present in PG. If I add a pic to a folder present it will detect the change but only if I swipe down to refresh. If I then open firefox and download some random picture to the downloads folder. If I open quickpic it will recognize that new photo in the downloads folder without user interaction and show the downloads folder. If I open PG, the downloads folder won't show up. Won't see it with a swipe down refresh either. Not until I open settings and then do a media scan which takes a good 10-15 seconds to appear. This is also 10-15 seconds I can't do anything in the app without worry about messing something up. 

Note: Search existing folders is checked in settings. 
Note: Folder is listed under included folders in settings.

Solution: Have PG be able to detect new changes to folders on the device without a time consuming media scan.

**Comment by puregallery** [comment]
Which Android version are you testing this on? 
Starting Nougat, Android has a new way to notify all apps about new media added to the device. Before that, there is a dirty way of 'observing' every folder on the device for new files...this essentially runs a service forever in the background to check for new files. I didn't like the approach frankly, so didn't implement that completely yet.
All other apps do that though...and I didn't find any good way yet. Looks like that is the only way to go...sigh

**Comment by Nostang3** [comment]
I'm running Nougat(7.1.2).

**Comment by Nostang3** [comment]
This now recognizes new photos very fast and with out media scanning. Kudos.

**Comment by Nostang3** [comment]
This still struggles to find some new folders without a media scan. Almost like the folder has to have been seen by PG at one time before it will detect a new file in the folder. It seems like once I've down the media scan it will detect that folder going forward.

**Comment by puregallery** [comment]
Is it a hidden or nomedia folder?

**Comment by puregallery** [comment]
I'm not starting that service if the device reboots...I see this as one reason. Let me test the hidden folder scenario and report back.

**Comment by Nostang3** [comment]
PG is still struggling to add new items to the view. I download photos a lot, and often they are download and created in a new folder based on username. So the root album might be sdcard/app/username/pic1.jpg. It doesn't recognize new folders added into the app directory still without a new media device scan from the settings menu.

**Comment by puregallery** [comment]
Is this improved now?

**Comment by Nostang3** [comment]
No, when a new folder and pic are added to the main folder it takes a media scan before it will show up in the album view.

**Comment by puregallery** [comment]
Finally figured it out...I was not looking for new folders being added to an existing folder. I was only checking for new 'files' added to existing folders. 
Man...feels good to be back :D

**Comment by puregallery** [comment]
Pushed an update...let me know if this fixes the issue for you.

**Comment by Nostang3** [comment]
This seems to be grabbing files in new folders a lot quicker and with a rescan.
