### ISSUE TITLE
Option to delete entire album

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#43]
It would be nice if you had the option to delete an entire album instead of going in and deleting a single file in the album. I have auto-download apps/modules running that automatically download images/videos and a app that syncs them to my gdrive. So sometimes I have folders that will autodownload a file and I want to delete it so it isn't uploaded. This would save a step from having to go into the album to just delete one file. 

This could either be accomplished by a long press then have a delete option at the top like a media file does now, or maybe add it to the three dot menu on each album in the main view.

**Comment by Nostang3** [comment]
This option does indeed delete the album. However, after selecting delete album it goes back to the album properties(right description?) of the album. You then have to clear the dialog then refresh the album view before the album is removed from the view. If you select the item before refreshing it will open up to nothing and it will list Pure Gallery as the working album.

**Comment by Nostang3** [comment]
I deleted an album and it takes about 10 seconds before it leaves the main view. Might even cause a crash when trying to enter the album during this time.

**Comment by puregallery** [comment]
I thought I showed a dialog until the delete is complete...lemme check.

**Comment by Nostang3** [comment]
It has a dialog that comes up, but it disappears and the album is still visible in the view. It wont' leave until you refresh the view.

**Comment by Nostang3** [comment]
Deleting an album now immediately removes the album from view.
