### ISSUE TITLE
Option: Backing out of album clears tag filter. 

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#46]
I use tags a lot and having this option clear out the filter on exiting album would be helpful.

**Comment by puregallery** [comment]
I can give this as a global setting...

**Comment by Nostang3** [comment]
That works for me.

**Comment by puregallery** [comment]
Do you remember why I added "preserving tags" for albums all the time? 
Now that I am revisiting this feature, I feel it is not so useful and I think the filters should be cleared every time you exit the album. Do you agree with this?

**Comment by Nostang3** [comment]
I don't believe you involved me in that decision. I think that removing them when you exit an album is fine. Usually when you exit an album or close the app you are done with whatever you were doing in the app.

**Comment by Nostang3** [comment]
Backing out of an album clears the set tag filter.
