### ISSUE TITLE
Ability to refresh an album while inside of it. (Pull down to refresh)

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#47]
When I'm taking a photo on my camera, I'll snap the picture, then switch back to PG and I'm in the camera folder. It would be nice if I could refresh while inside of the folder. Otherwise I have to go back out and refresh the main view then go back into the folder.

**Comment by Nostang3** [comment]
I am now able to pull down to refresh inside of an album and see a new photo added to it.

**Comment by puregallery** [comment]
Found an issue with this implementation..

**Comment by puregallery** [comment]
Are we still seeing this?

**Comment by Nostang3** [comment]
No, if I snap a picture with the camera app it still doesn't update the number of files in the camera album. But I can swipe down to refresh and it does appear. So the problem is gone. Closing.
