### ISSUE TITLE
PG is crashing( Refresh issue?)

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#51]
I noticed that I have been getting crashes lately. I know one happened after I deleted an album and it didn't remove itself from view so I tried to refresh it. The album stayed after the refresh animation stopped. Then I tried to enter the folder and it didn't do anything. After a few seconds the album disappeared and the app force closed.

**Comment by puregallery** [comment]
Yes...Just saw the crash in play console...fixing it soon.

**Comment by puregallery** [comment]
pushed an update...let me know if its fixed.

**Comment by Nostang3** [comment]
I'm still able to get it to crash when deleting and album and then trying to view it before it's removed.

**Comment by puregallery** [comment]
Try the 95 build..just pushed it.
Latest release had some on-off work...didn't finish a few refactors on time and got to work on them after a long break....I lost track of the progress and a slight Spaghetti code ensued. Sorry about that.

**Comment by Nostang3** [comment]
It no longer crashes when trying to enter a deleted album.
