### ISSUE TITLE
Tag+ will remove existing tags and only add new tag

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#57]
There is a case where using the tag+ option will remove all tags already set and just update the new tags. Might have to do with the using the Change Tag option being used at some point before using the Tag+ option.

**Comment by puregallery** [comment]
I was not updating the tags while using the Change Tag option till now...but the icons are doing their job fine.

**Comment by puregallery** [comment]
Whoops...correction...was overriding the tags...your observation was correct 👍

**Comment by Nostang3** [comment]
I've done some tagging and I haven't seen it overwrite previous tags.

**Comment by Nostang3** [comment]
Just tried to tag an individual pic using the 'Change Tags' option and it overwrote the existing ones and just added the new one.

**Comment by Nostang3** [comment]
I don't believe I have seen PG overwrite any tags since the update after this comment. I will close this for now and open it if I see it happen again. 

RC4 released at the time of this posting.
