### ISSUE TITLE
Adding second tag to filter crashes PG

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#59]
If you filter by tag, then try to filter again and select another tag and hit apply it crashes pg.

**Comment by Nostang3** [comment]
It will also crash when just clearing a tag.

**Comment by puregallery** [comment]
I'm guessing this is fixed...can you try this on the RC1 and report back?
Btw...i'm tagging things appropriately to the milestone 'Release Candidate 1' now

**Comment by Nostang3** [comment]
I did some quick tag filters and I couldn't get it to crash. I'll close this for now, and open it back up if it happens again.
