### ISSUE TITLE
When moving pics, it doesn't fully accept the move til you swipe down to refresh at album view

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#60]
If you go into a album, and move one or more files(in this case emptying the album) then back out after it shows no pics present, it will update the moved to folder number count but the original album will still be shown. If you go into the moved to folder they won't show up. You have to back out, swipe down to refresh, then the original folder will disappear and the move to folder will now show them when you go into it. 

Also, in regards to old issues, it's hard for me to know which ones are done and for what version since you stop using milestones for new updates.

**Comment by puregallery** [comment]
Oh, everything marked as finished work are released at the moment. I'll look into these issues in the next release.

**Comment by Nostang3** [comment]
When moving a file from an album, emptying it, then backing out, the empty folder will disappear but the folder you moved it into won't update it's count, and if you go into the album, it won't show the new photo till you swipe down to refresh.

**Comment by puregallery** [comment]
In my testing, the swipe refresh is automatically invoked...and that is how it is defined too.
Did you not see the automatic refresh be triggered?

**Comment by Nostang3** [comment]
The swipe to refresh animation appears but the album cover nor item count updates until I do another swipe down to refresh.

**Comment by Nostang3** [comment]
I have used this app for a few days now and I haven't ran into an instance where it didn't properly display the file changes.
