### ISSUE TITLE
Empty Favorites

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#61]
After opening the left hand menu and trying to click on favorites it will crash PG everytime.

**Comment by puregallery** [comment]
This is released

**Comment by Nostang3** [comment]
My favorites section is empty. I double checked a photo and it is hearted. I ran a media scan in settings to see if it needs to scan the files to readd them back into the favorites section but that didn't work. Favorites doesn't crash now though, so that's a win.

**Comment by puregallery** [comment]
Ah, I see the issue...will fix. Lets keep this open and edit title

**Comment by Nostang3** [comment]
For what's it worth, my favorites have returned again in RC3.

**Comment by puregallery** [comment]
Umm...do you mean the crash or the bug is back? or is it working fine now?

**Comment by Nostang3** [comment]
It's working fine now. Or at least my favorites is now populated again. They look to be the correct ones I favorited before.
