### ISSUE TITLE
Can not enter Tag mode while viewing a photo

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#63]
Since you added the nice information at the corner of the screen, it's given me an easier way to view tags associated with pics. As I expand my tags, I want to go back through and check older photos to make sure I can't add more tags. Currently, I have to back out of the photo, long press, then choose tag mode to add a tag. Be nice if there was a more direct way.

**Comment by puregallery** [comment]
So you just want an option to add tags to a single photo right?
Also, I'm planning on giving an option to open a 'selection' from Album in the media viewer. This might help a bit for your needs as well

**Comment by Nostang3** [comment]
Yeah, while just viewing that one, a quick way to enter tag mode for just that photo. That way I can swipe, find a photo that needs to a tag added, enter tag mode, tag, then exit tag mode, and start swiping through photos again.

**Comment by Nostang3** [comment]
My only complaint about this is that the Edit Tag option is in the Three Dot Menu instead of on the bottom bar but I understand that you probably don't want to clutter the bar. 

Is it possible to add a Edit icon to the left of the tags on the info bar to Edit Tags? This would prevent a cluttered bottom bar while also providing a quick way to edit tags. I attached a picture of the mock-up icon and placement. 
![screenshot_20180812-195828](https://user-images.githubusercontent.com/25465114/44007861-40b483f8-9e6a-11e8-9cf7-311cd209bc3a.jpg)

**Comment by puregallery** [comment]
Since your suggestion is to market the app around tagging, it makes sense to include it here. Lets try having it for a few days and see how it looks.

**Comment by Nostang3** [comment]
Same with this case. Update it to the next version since you are changing it's behavior.

**Comment by Nostang3** [comment]
I see that you added the Tag option to the info bar. I think it's nice. It's a quick way to edit the tags and get back to viewing photos. I can report back after a few days if you want after I give it a run as I add new photos.

**Comment by Nostang3** [comment]
The tag option will in media viewer is nice and I use it quite often.
