### ISSUE TITLE
Add slideshow option to album

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#64]
Maybe with basic customization options, duration, shuffle or sequential, etc.

**Comment by Nostang3** [comment]
When clicking on the interval drop down option it opens a blank black dialog. I'm using the black theme. Switching to a different theme shows the seconds in drop down. I think the text on the black them might be set to black color.

**Comment by puregallery** [comment]
Ah, first spinner/dropdown in the app...forgot to theme it properly.

**Comment by Nostang3** [comment]
Might want to change the milestone to the next version since the black theme isn't right yet.

**Comment by Nostang3** [comment]
The Seconds option now shows in the Black theme for Slideshow options.
