### ISSUE TITLE
PG occasionaly forgets what files are in the album

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#65]
There have been times where I add a new pic to an album earlier in the day, then come back to the album alter and it's not there at the top of the list(Sort and group by date). If I do a pull to fresh it shows back up.

**Comment by Nostang3** [comment]
I still saw this happen just this morning. I copied some files into an album within PG and I then went into the album at a later time and they weren't there. I had to swipe to refresh to get them to appear. For the most part they usually show up but sometimes, they don't. Will comment if I can figure out any steps to recreate.

**Comment by puregallery** [comment]
Forgot to push this change in the release..
