### ISSUE TITLE
When exiting viewer, the position of where you were in the album moves

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#67]
It seems that sometimes when I exit the viewer, it will scroll itself up quite a ways(2-3 screens worth). I closed out of PG and went back into it and it seems to have corrected itself. Wanted to make the issue, just to note it.

**Comment by puregallery** [comment]
The album scrolls automatically to bring the last viewed image onto the screen...
You can open the media viewer from the first item...but if you scroll thru the viewer till 50th item, the album will scroll till that position when you go back to it.
Is this what happened?

**Comment by Nostang3** [comment]
No, if I view just one photo and back out, it jumps up a few pages. It doesn't happen all the time. There is definitely something that triggers it and closing the application fixes it.

**Comment by puregallery** [comment]
I haven't seen this till now...let's keep this open until I figure this out
