### ISSUE TITLE
Changing exif data causes PG to exit album

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#68]
In my case, I'm sorting by tag and comparing photos. Since I'm sorting by date, I find some photos that I need to correct the capture date, and after doing so, when I pull to refresh, instead of the file moving to the new grouped month, it completely exits out of the album. I lose the tag filter and the the location of where I was at. 

It would be nice, if PG could handle the exif data change gracefully adjust it's sorting without exiting the album.

**Comment by puregallery** [comment]
At the moment, the app doesn't read exif again on existing images...it is done only through a media scan. It scans exif for newly added files automatically though.
Either way, exiting the album is a little concerning.How did you edit the exif? I want to reproduce this scenario and see what happened.

**Comment by Nostang3** [comment]
I share the photo to an external application, as it's the quickest method to do so. I share it to Photo Exif Editor and I can quickly change the capture date and exit back into PG. Then after a few seconds it will exit the album. 

Note: if I exit the album before PG does it for me then it doesn't do anything. If I swipe down to refresh, you can see PG create an album for the photo, then quickly delete and it will then be in the proper place in the album. I forgot to add a case for this issue.

**Comment by puregallery** [comment]
Ok...I will look into that...
Btw, it is not a big deal to add our own exif editing feature in the app. I'll look into having this in

**Comment by Nostang3** [comment]
I've changed the exif data on a few photos  and PG no longer crashes. It doesn't see the new exif changes until a media scan is run.
