### ISSUE TITLE
Customize Filter Experience

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#69]
Crappy title.

When going to filter, I always filter by tag. It would be helpful if this was the default option or make it a way to be default. 

When filtering, I commonly filter the same tags. It would be helpful if there was similar customization options for filtering as there was for tagging. i.e. Frequent and Alphabetical.

**Comment by Nostang3** [comment]
It looks like the change you made here was setting the 'Tag' tab to default? Am i correct in that assumption?

**Comment by puregallery** [comment]
That was one part of the solution...the other part is introducing the 'frequent', 'recent' etc filters

**Comment by Nostang3** [comment]
I also noticed that there are numbers next to the tags. Is this intentional or left over from debugging? If intentional, you might consider adding a space between the tag and the number for better readability. 

Also, maybe think about adding a way to distinguish which filter is applied. Maybe highlight change the color of 'Recent', 'Frequent', or 'Alphabetical'. Could also flip the filter button for 'Alphabetical' so you can see if it's sorted ascending or descending. I could see where 'Frequent' and 'Recent' might show the same visible items and you might not be sure which filter is applied. Might be a nice touch to help with intuitiveness. 

The apps is coming along nicely. Can't wait for you to get into a released version. I hope you get a lot of users on it. I think that tag functionality will take off once you can promote it to heavy media users.
