### ISSUE TITLE
Back button clears sort filter before exiting album

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#70]
I do a lot of tag filtering, and would make things easier/quicker if the back button would clear the filter as a precursor to leaving the album. This can speed up changing filters or clearing them without having to go into the menus.

**Comment by puregallery** [comment]
We should not change back button's behavior frankly.
I'm thinking of clearing all filters on a long click on the menu item...or have a floating button show up when album is filtered.
Which one do you prefer?

**Comment by puregallery** [comment]
Clearing selections is a considerably visible UI change -- bottom bar hides and image overlay is removed, action bar icons change

Clearing a filter might not be too obvious to many people. 

I will include a floating button which will hide when the list is scrolled down.

**Comment by Nostang3** [comment]
The floating button clears the tag filters as expected.
