### ISSUE TITLE
Tag list in Info Bar is not alphabetical

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#71]
This would probably classify as more of a nitpick than bug but if you're quickly going through photos, checking to see if that tags match the file and if you need to add more, having them alphabetically listed would be helpful. I'm sure the issue stems from how it reads the information from the picture itself as they are probably not written to the file in alphabetical order.

**Comment by Nostang3** [comment]
Just a note, I emphasize a lot on tagging because I think it's important for your app. I don't want to seem like my bugs/enhancements here are geared toward what I want and not the app itself. I just believe that the android market is saturated with gallery apps. But what they don't have is apps that allow a comprehensive way of dealing with those photos. I think by focusing on the tag aspect of the app you can set yourself apart from all the other gallery apps out there. You'd really be alone in that market. I've looked at a lot of gallery apps and none of them really handle tagging.

**Comment by puregallery** [comment]
No worries...I welcome all kinds of suggestions.
Frankly, the space for gallery app looks saturated already. I even thought of open sourcing the code, but am worried about people creating clones and uploading their own versions.

I'm confused as in how to monetize this app. I don't think people would prefer ads in a gallery app...So, the logical way is to limit features in the app based on some kind of in-app purchasing. Which features do you think should be behind that pay-wall?

If you don't mind, can you pour your thoughts on this matter for me...

**Comment by Nostang3** [comment]
I think they should revolve around the tagging feature. Maybe allow tagging to be free but the more intricate features of tagging locked behind the premium option. Since it's the the defining feature of your app. It's what sets you apart from all other gallery apps.

**Comment by Nostang3** [comment]
Tags are now sorted in info bar when viewing photos.
