### ISSUE TITLE
RC2 Lumps all pics sorted by 'Group By' into one group. 

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#73]
All my photos are currently showing in a 'July 2018' Group. Even if you switch it to day, they all group into today's date. I tried switching to different sort by options but nothing changed. 

I was finally able to get it to recognized the correct sort groups but they are all out of order by doing a media scan. Currently it is going:

July 2018
December 2015
October 2017
January 2016
Etc...

Filtering by tag while in this state crashes PG. If I remove group by and group by none, I am able to filter by tag again.

**Comment by puregallery** [comment]
Ah, was worried what the changes to Date Created might turn into...can you run a media scan and let me know if this still exists?

**Comment by Nostang3** [comment]
I ran one during troubleshooting and it got them to populate but in the wrong group order. I ran a second one and they are still out of order.

**Comment by puregallery** [comment]
Can you post a screen shot of the exif info where the date created is shown? I need to see which field it falls under. I need to see a few fields above and below that value if possible.

**Comment by Nostang3** [comment]
![1532972387727](https://user-images.githubusercontent.com/25465114/43413504-34b4d434-93fe-11e8-9fb1-39d9cc33e6e9.png)

**Comment by Nostang3** [comment]
I tried clearing the data for the app and all it did was shuffle the order around of how they were grouped.

**Comment by puregallery** [comment]
Thanks for the screen shots man...it tells me the Date Created implementation is buggy...I can now see the issues you had a while back in another bug. I will undo this change for now and work on this later on.

**Comment by Nostang3** [comment]
I believe this issue is fixed, right?

**Comment by puregallery** [comment]
Yes...this is fixed. Closing it off.
