### ISSUE TITLE
Some albums aren't opening the correct photo

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#74]
I noticed that in some albums it's opening the wrong picture when clicking. It's like the order of the files aren't associated with the thumbnails correctly. Some albums work fine other don't with the same album settings.

**Comment by puregallery** [comment]
Dang it...I will undo the Date Creation changes to minimize these bugs...looks like it needs more testing.

**Comment by Nostang3** [comment]
Unchecking Date Created puts them back into one big group of this month.

**Comment by puregallery** [comment]
I reverted the changes back...is this still happening?

**Comment by Nostang3** [comment]
Yes, in the albums I checked(which some are the same, others have been removed by online backup) all pictures were correctly displayed.

**Comment by puregallery** [comment]
I have a debug build to test the new changes to this 'date created' field. Are you open to take up a debug build and test it out before i push it to the play store? This build can be installed along with the version from play store...it essentially has a different package name.

**Comment by puregallery** [comment]
https://drive.google.com/open?id=1zaJfzGbiP4FEZFhR6UmTFbd3CBt1T2Lg

Use the apk from here...perform a full media scan and see if the date created feature is working fine. 

When the files don't have date created in their exif, it defaults to the date modified.

**Comment by Nostang3** [comment]
This seems to installed over the original PG because I can't find a separate app in my tray and when I open it, it gives me an error that says "App not installed from Play store. This will not be allowed in future releases."

And running a media scan, does the same thing it did before. The Month groups are all out of order.

**Comment by puregallery** [comment]
Ah, shoot...my bad...wrong build.

That toast is normal...apparently some one in Russia uploaded my app to their store.

**Comment by puregallery** [comment]
This has been fixed too.
