### ISSUE TITLE
PG doesn't see modified date correctly for PNG's / PNG doesn't support Date Created metadata?

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#75]
EDIT: Putting this at the top because the post is long with photos. I couldn't get PG to recognize the new date with pull down to refresh, scan for missing folders, or a media scan in settings. I had to force close PG and open it back up and they moved.

My PNGs are showing up at the top after writing tags to them because the modified date changes. I have went in with File Commander and changed the modified date to a different date but they still stay at the top. 

I have attached some pictures to help. The first one is media info button infromation and you can see the modified date is set for 01/01/1999 but shows in july 2018 group. 
![exif_media_modified](https://user-images.githubusercontent.com/25465114/43614132-25ee6f8a-9680-11e8-9054-c6e242a8e2fa.jpg)
The second shows a second field(probably the same one in exif). 
![info_button](https://user-images.githubusercontent.com/25465114/43614133-25fff516-9680-11e8-83e6-926e7df03714.jpg)

This one shows a metadata marking the profile date/time field. This is probably when picture was taken but I don't know sure, the year seems right for the context of the photo. Might be able to use this as a field for creation date for png files.

![exif_media_profile](https://user-images.githubusercontent.com/25465114/43614296-d1a7a102-9680-11e8-9b68-9baef3d8ffdf.jpg)

**Comment by puregallery** [comment]
>I had to force close PG and open it back up and they moved.

This needs more time to look into...definitely a concurrency issue.

Did the media scan finish when u were in this state? Btw...only a media scan will attempt to refresh information on media files. Rest all methods are simply to find missing files.

The profile date/time is a new EXIF tag that I'm seeing. Do you mind sharing the image with me if it doesn't have any personal information? Else, I can give you a build to print out the entire exif for us.

**Comment by Nostang3** [comment]
Here you go. No judging on the image in questions. ;)
![1383529_715670455193693_8698113633320472717_n](https://user-images.githubusercontent.com/25465114/43671565-717327d0-976a-11e8-801d-636fd71fcd52.png)

**Comment by puregallery** [comment]
haha...no worries...thanks for the image 👍

**Comment by puregallery** [comment]
The date on this picture is not in the regular PNG format...but a rather peculiar place. This picture helped me track it down...thanks again 👍

**Comment by puregallery** [comment]
Also, it isn't really the standard time on any image. It is apparently a profile's creation time on a device(scanner, camera etc)

https://photo.stackexchange.com/questions/82495/what-does-the-exif-icc-profile-date-mean

Should we keep it or remove it?

**Comment by Nostang3** [comment]
It's sad that png spec doesn't support any kind of date created metadata. And the ones you can create differ between devices. I say I guess not worry about it. I'll just modify the file modified date to get them in the right place until I can replace them with jpg files.

**Comment by puregallery** [comment]
Btw...am working on the exif editor feature atm...stay tuned...
Android supports editing Exif for Jpeg's only though.

**Comment by Nostang3** [comment]
That's great, can't wait to try it out. Everything I download now is in .jpg anyway. I just had a few pictures in my album that are png.

**Comment by Nostang3** [comment]
I see the Edit Exif option and it looks comprehensive. 

I noticed that the three dot menu is supposed to show the clear option but it is missing on the black theme. I can see it on another theme if I switch.

**Comment by puregallery** [comment]
Yes, the exif editor will give you options to edit all available properties...I'm thinking of giving an option to change just the date in the add tags screen though.
I'll look into the black theme issue..

**Comment by Nostang3** [comment]
I agree that a simpler option might be better in most cases. I don't know what most of the options are in the exif metadata and all I will change is the taken date.  You could just prioritize the options for this app and leave the in depth options to other apps. Stuff like taken date, gps, maybe a few others. BitsPerSample and CFAPattern probably don't need to be in there. Well that's my opinion.

**Comment by puregallery** [comment]
It will be helpful for professional photographers...which is one of my hobbies as well
Eitherway, what I have right now is a full-fledged EXIF editor. I plan to have a minimal editing option as well to minimize the complexity in there.

**Comment by Nostang3** [comment]
I attempted to edit a png exif and saw the new warning dialog. I believe this case can be closed since the original issue is not fixable.
