### ISSUE TITLE
Album cover holds previous thumbnail instead of new one

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#79]
I have a folder with one file in it. I deleted that file then later a new file is added to the album. The album cover shows the previous thumbnail of the folder. Swipe down to refresh on view of all albums doesn't change it. Rescan folders doesn't change it. Media scan doesn't change it.

**Comment by Nostang3** [comment]
PG now uses the new image added to directory instead of the previous photo.

**Comment by Nostang3** [comment]
I just saw this issue again in RC4. Holding the wrong image for the album cover.

**Comment by Nostang3** [comment]
Saw this happening in RC6.

**Comment by puregallery** [comment]
Yeah...i came across this one too. Easy to debug now.

**Comment by Nostang3** [comment]
I moved/copied/deleted files from/to a folder and the album cover always seemed to be update and current, especially without having to refresh the view to make it happen.
