### ISSUE TITLE
Deleting a photo while Filtering Tags causes PG to crash

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#80]
If I add a new photo to PG, tag it with a couple tags for search purposes, then filter the album with those tags so I look for duplicates. Then when I find the duplicate and compare then delete the newly added file it will cause PG to crash. Crash doesn't seem to happen when not using the Filter Tags option.

**Comment by puregallery** [comment]
Yes, I found this bug too...it is a bug in one of the library that I am using...waiting on a fix from them.
Else, need to drop the library I guess.
This randomly happens when you clear the filter as well.

Edit: This happens only when the list is grouped.

**Comment by Nostang3** [comment]
Is there a way to handle the exception gracefully in the meanwhile? Maybe just note the error with a dialog and revert to a default album view settings?

**Comment by puregallery** [comment]
I will look into that.
But the crash is in another library...no clean way to catch it.

**Comment by Nostang3** [comment]
I have deleted a bunch of photos while in filtered view on numerous occasions and PG has not crashed.
