### ISSUE TITLE
Edit Exif Issues

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#81]
I noticed that sometimes it prompts the keyboard to appear and there is no way to get the keyboard to disappear. It hides the Ok button to save. 

I also noticed there is no way to change the time of the photo as well. The time is helpful when you have more than one photo on the same date but you want to group them. Say some are of cats and others dogs but you use the time to make sure they aren't mixed.

**Comment by puregallery** [comment]
>It hides the Ok button to save.

Is this referring to the button on keyboard? or the actionbar?

**Comment by Nostang3** [comment]
I guess I didn't describe it fully. My bad. It's the Ok button the calendar. When my keyboard(SwitftKey) is open, it covers the Cancel and Ok button. The keyboard is opened by default when you enter the Edit Exif section. 

Edit: You can eventually hide the keyboard to hit the button but it takes a couple extra clicks and if you aren't using the keyboard for something like the date captured then it's always a couple extra steps.

**Comment by Nostang3** [comment]
Just a thought when you get to working on this, it might be helpful to take note of the date entered for date metadata and display the same date again for the other fields. There are three Date fields and if you enter in the date time for each field you have to manually edit the calendar to the right date, it might be helpful if when you open the calendar again for another date field it has the date for the previous entered. Then maybe have a button that can automatically move the date to today if needed.

**Comment by puregallery** [comment]
Only one value is required for us to manage it ideally...i am looking into providing a mini EXIF update UI to change things quickly.

**Comment by puregallery** [comment]
What values would be ideal for this mini exif editor? Date is one value...i can't think of any others. Managing latitude/longitude is a pain and not easy for everyone frankly.

**Comment by Nostang3** [comment]
Besides date I think maybe copyright/artist.

**Comment by Nostang3** [comment]
My only complaint is that the keyboard is opened by default when entering "Edit Exif". It looks might be defaulted to copyright which you'd enter text. They keyboard being open at the beginning causes a problem if you are going there to edit the DateTimeOriginal field. It brings up a calendar and the Ok/Cancel buttons are hidden by the keyboard. 

Is it possible to not set the cursor active in the copyright field and let the use choose the active field? 

Also, there is no option to set Time for the DateTimeOriginal, only the date. It seems like it sets the time based on when the field was edited. Since PG can sort photos by creation date having the option edit the order of photos by adjusting the time would be helpful.

**Comment by Nostang3** [comment]
It looks like the new calendar doesn't account for the black theme. It comes up white and the highlight is missing. So the dates 14(date of picture) and 15(current day) aren't showing up on the calendar. If I change the theme to a light theme and go back and view it, then the days are there.

**Comment by puregallery** [comment]
sigh...this is the second time I forgot the black theme on the same screen. Will fix.

**Comment by Nostang3** [comment]
You might check other areas as well. I noticed that when using the Floating button on filters, it disappears when you open the Recent, Frequent, Alphabetical. You can still press the button to minimize the options so it might just be black.

**Comment by puregallery** [comment]
That's one challenge I constantly faced with UI elements that have multiple states/colors to indicate available actions.
For now, I will break the AMOLED theme for similar widgets until I figure out a better way to distinguish them...meaning, the icon there will be green/white for all themes.
