### ISSUE TITLE
RC4: Hidden albums will sometimes be visible when opening PG

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#83]
So I have a hidden album and have PG hide it when I exit the app. When a couple new files were added to the album, when I went into PG to check to make sure they were there, PG said there was 2 files in the album out of the 4 total. Toggling 'Show Hidden' to show all the hidden albums seemed to correct it because hiding albums no longer showed the album. 

Steps:
1. Have a hidden album with files in it. (Not sure if they need to be visible when you close PG)
2. Close App to make sure PG hides albums.
3. Download new files to the album.
4. Open PG.

This issue doesn't happen all the time as I deal with this particular scenario on a daily basis. I'm not sure if it was just a fluke in Androids Media Scanner or an actual issue with PG. Just noting it for future reference.

**Comment by puregallery** [comment]
I follow these steps almost everyday and never saw it...the OS version will affect how this behaves.
Are you still on Nougat? I am using Oreo atm

**Comment by Nostang3** [comment]
Yeah, I'm on 7.1.1.

**Comment by puregallery** [comment]
RC5 handles hidden files much better...give it a try and report back

**Comment by Nostang3** [comment]
I am still seeing hidden albums visible when starting up PG. I imagine they disappear after the initial start scan.

**Comment by puregallery** [comment]
How did you hide the folder? Did you add the noMedia file? or is the directory named this way - .directoryName ?
This is really peculiar...i am not able to reproduce this at all.

**Comment by Nostang3** [comment]
I either have .nomedia file in the directory or used the hidden option in PG which I assume puts a .nomedia file in the directory?

**Comment by puregallery** [comment]
PG uses the no media file, yes.
 But you can manually hide the folder by adding a period in front of the folder name. Was just wondering which one you used.

**Comment by Nostang3** [comment]
I understand. I read that you could use the .foldername method lately but I've never used that option in all my time on android. One day if I get bored I'll have to research what the benefit of the folder one is or when that is better to use than the .nomedia file.

**Comment by puregallery** [comment]
Don't know the benefits myself frankly.
Either way in this bug, did all of your hidden folder become visible, or just one/few?

**Comment by Nostang3** [comment]
It's seems like it's ones that were empty or emptied since the last time PG was ran, then a new file was saved into it, which prompted me to go to PG to look at it. It then shows up for a second before it does the scan then disappears.

**Comment by puregallery** [comment]
Ah, this explains. I just ran into this today. So when a file is added, I don't check/care what status the folder is in and just add it my database...the app doesn't know that it is a hidden folder until a full scan on the directory is performed.

**Comment by Nostang3** [comment]
I'm going to leave this one open, because there has been a rare case where the hidden toggle option wasn't checking correctly and it showed the albums when it shouldn't. Toggling the option twice got it back on track, just not sure how it was triggered. I think it was resuming but not sure.

**Comment by Nostang3** [comment]
I think this is similar enough to include in this case but let me know if you want a new case. I've mentioned before that sometimes when loading PG that it will be empty. I believe this happens when you are inside a hidden album and then leave the app by going home or switching to a recent app. Then PG will exit and reset the album visibility to hidden but won't reset the last known position to home so when you go back into PG it tries to put you in the last known location of the hidden album but since it's defaulted back to hidden it shows empty.

**Comment by Nostang3** [comment]
So, after some more usage, I realized that when it happens I can swipe down to refresh and make the non hidden albums appear.

**Comment by puregallery** [comment]
Yeah...I have a fix for this ready. But it needs a bit of testing before pushing this out. 
I am taking a week-off after thanksgiving to finish the release of this project.

**Comment by Nostang3** [comment]
I saw this issue this morning. I hadn't used the app for probably at least 8 hours(slept), and when I came back the hidden albums were still visible. I think I might have hit the home button to leave the app or swapped to a recent app instead of backing out. This also made the toggle become unsynced. When I toggled hidden albums on, nothing happened, well because they were already not hidden, but toggling it back off synced the toggle back correct again.

**Comment by puregallery** [comment]
Most of this is expected behavior frankly since you didn't restart the app...
The only issue I see here is the toggle not reflecting the actual state. I will look into that.

Btw...am working on a new layout for the home screen...similar to Google Photos app with bottom navigation. I will have an option to toggle between the old and new layouts.

**Comment by Nostang3** [comment]
I think that would be neat.

**Comment by Nostang3** [comment]
I think you can close this then, if it's intended behavior?
