### ISSUE TITLE
General PG media issues

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#84]
It seems since in the last couple versions that PG is having trouble with being aware of the media on the device. 

1) If you add new images to an empty folder, it doesn't show them when you open PG. Doing a swipe down to refresh, doesn't make PG see them. I'm constantly having to open PG > then three dot menu >'Search for missing folders' before I can see new images. 

2) Conversely, if files are removed from a folder and it's empty, when you open PG it still shows those folders and the pictures in them. You can click into a folder and still see the photos but you can't open them in media viewer. It just opens to a black screen. And swipe to refresh in album view either doesn't remove the empty albums or I have to swipe multiple times before it removes all empty folders.

**Comment by puregallery** [comment]
I need to start using devices below Oreo I guess...will look into this. Btw...sorry for the delay in pushing a build. Will be having one out this week.

**Comment by puregallery** [comment]
Is there any way you are limiting the background services on your phone through developer settings or through xposed? The app runs a service in the background to be notified of any file being added/removed to the storage. From my testing, I can definitely say that things are good when the service is not interrupted/killed. I'm guessing the service is somehow being killed on your device. Do you use the 'long-press back to kill app' or anything similar?

**Comment by Nostang3** [comment]
No, I leave the app running and only force close it when I have an issue with it or troubleshooting. 

Now that you mention background service. This Pixel XL seems to be VERY aggressive with battery optimization. I know with instagram, when I get push notifications, I used to only sometimes get the image that came along with it. I had to turn off battery optimization and now I get all the push images. I wonder if Android is killing whatever service you have for battery optimization. I'll turn it off for the app and see how that does.

Also, I should note that another gallery app like Camera Roll always detect new files/folders on launch. I just wanted to mention it in comparison. Could be it just auto scans on launch.

**Comment by puregallery** [comment]
I think they auto scan on launch...which we have an option to disable it in our app. Maybe we should run the auto scan during startup to avoid these discrepancies

**Comment by Nostang3** [comment]
I have the "Search Existing Folders for new Media at Start-up" checked but it doesn't seem to do that. I could see where that might be folders that it has already found and just update new files in that folder but it doesn't even do that. I either have to manually pull down to get it to refresh the number of file sin an album or go into the album and do a pull down refresh.

**Comment by puregallery** [comment]
I am planning on removing that option in settings since there are many scenarios where the process could've been killed. Going forward, we will always search of new media at startup.

>I could see where that might be folders that it has already found and just update new files in that folder but it doesn't even do that.


Let me look into what's causing this

**Comment by Nostang3** [comment]
Update: Turning off battery optimization for PG didn't help it with media discovery.

**Comment by Nostang3** [comment]
Could the issue be related to hidden folders? It seems like PG finds folders that aren't hidden fine, but the ones that are, always have to be scanned for.

**Comment by puregallery** [comment]
Ah, that explains. Hidden folders always need to be scanned...yes. They are considered 'not important' by the OS usually. So, the extra scan is always necessary. When you pull down to refresh, I check for the hidden folders setting and scan the folders based on it.
Even if 'scan for directories at startup' is enabled, and 'show hidden folders' is disabled...I don't scan for the hidden folders to speed up the startup process.

**Comment by Nostang3** [comment]
Ah, 90% of my PG usage is dealing with hidden folders.

**Comment by puregallery** [comment]
So, shall we have a setting for 'scan for hidden files at startup'? Or leave this as default?

**Comment by Nostang3** [comment]
I think we should scan for all files hidden or not in the folders we set to monitor. Because even if you scan for hidden files, you wouldn't see them until to you toggle the option. I don't see the need for that extra step of having to toggle hidden and then have to rescan the folder to see the files. BUT...my opinion might be slightly biased since I deal with mostly hidden albums. :)

**Comment by puregallery** [comment]
Let's try this for a while...
I actually got feedback from a few users that the startup process is slow...I am a little worried on how this might affect them. Then again, not sure if they would have hidden folders.
I will push the update tonight

**Comment by Nostang3** [comment]
PG is not as quick as Quickpic is/was(I still have it installed) but it's on par with Camera Roll as far as opening to Album View. 

Maybe you could do a compromise and only scan for hidden files when the Show Hidden is toggled. This would allow you to have the the speed at startup but also show hidden when needed. You might put a disclaimer that when 'Show Hidden Directories' is checked that it can slow down app start times.

**Comment by puregallery** [comment]
>PG is not as quick as Quickpic is/was(I still have it installed) but it's on par with Camera Roll as far as opening to Album View.

Yikes...
I know that the underlying database operations are taking a huge toll on the speed. I have plans to migrate the database to a much faster/better version. But that will pose some challenges. I might have to force users to perform a full media scan after the update...or worse, to clear the data. That aside, the work itself is huge and needs a lot of testing. I better get started on this I guess.

**Comment by Nostang3** [comment]
First Impression: I just had to use the "Search for Missing Folders" option to get folders to show up. Just so we are clear these are folder that will have files in them, then get emptied as my sync service removes them from the device every few hours. So PG(RC5) is missing folders that are not currently viewable in PG because they weren't present the last time the app was used but now have files in them upon start up. So it's either not scanning for them or not updating the view after it scans. Next time I'll refresh before scanning to see which it is.

**Comment by puregallery** [comment]
>So it's either not scanning for them or not updating the view after it scans

It is not scanning them. When any album is emptied, I delete it from the database and PG does not have any idea about that folder until 'scan for missing folders' is invoked. I understand how critical it is for the scenario you mentioned. I need to stop deleting empty albums from the app.
Also, I am changing the basic architecture of the app to speed up the whole process...eventually reducing its memory usage so that image loading can take more priority. I am literally scared of this task. Hope nothing gets messy. 
I've decided to make current users go through this now than at a later date...it is a lot faster from my initial testing 🚀 
Once the current architecture is stable, I'll give you a test build to play with it...that's at least a week out.

**Comment by Nostang3** [comment]
Not sure if you want a new case for this, but if you 'Search for missing folders' then enter a album before it completes, and back out after it completes, the album view won't refresh with the newly added folders. You have to swipe down to refresh.

**Comment by puregallery** [comment]
Yeah...I know about this bug. Hopefully I can address this with the new architecture.
Either way, the new architecture is close to being stable. Are you interested in testing the debug version? 
I will make sure that you can have both versions installed simultaneously.
The speed increases have been good so far...full-mediaScan on my device finished in 170 seconds, while previously it was 240. App startup is quite fast too..didn't measure the difference yet.

**Comment by Nostang3** [comment]
Yeah, I don't mind at all as long as they are separate version so I don't have to be using TB+ to restore and such.

**Comment by puregallery** [comment]
Use the build at this. You can install it along with the original build.

https://drive.google.com/open?id=1HhkcpQv9wN1RhU1cH_dEIAgNyu9V4bBf

**Comment by puregallery** [comment]
Finally found the bug regarding media not being updated appropriately...

**Comment by Nostang3** [comment]
Just to note on DEBUG, it loads a bunch of empty folders and says that they have media in them, when they don't. And if you try to click on the items it says the folders have it doesn't load anything. Since it was a 'new' installation, I ran a media scan but the folders weren't removed. Search for missing didn't remove them either. 

Edit: The files that it fails to load still show info data like size and dimensions and date. Some folders might show items in them like the other empty folders except when you go into the folder it doesn't actually have anything in them which it doesn't.

**Comment by puregallery** [comment]
I am looking into the empty folder issue...I need to hold on to them somehow for media to be refreshed properly. How is the app other than this issue?

**Comment by Nostang3** [comment]
Well just now opening it, it lost my visible folders like the camera album. A media scan brought them back. I feel like it's a more responsive to load from a closed state than the stable version.

**Comment by puregallery** [comment]
Yes...that was my impression as well...slightly unstable at the moment...but feels fast.
So, the initial mediascan didn't find your camera album? Can you tell me the relative path for ur album? /sdcard/DCIM/Camera ?

**Comment by Nostang3** [comment]
Yeah the default directory. Inside of PG it is listed as /storage/emulated/0/DCIM/Camera. 

It seems to lose the camera album. It didn't show back up after reopening the Beta.

**Comment by puregallery** [comment]
Do you have multiple albums/folders named "camera"?

**Comment by Nostang3** [comment]
There is only one Camera album in the DCIM folder. I checked other possible media folders and I didn't see another camera folder. I did a search with Root Explorer on the SD card and there other folders with camera in the name but none that are just 'Camera'.

**Comment by puregallery** [comment]
i uploaded a new build with a fix to the empty folders...can you try the new build from the same folder?

**Comment by Nostang3** [comment]
The second build still showed the empty folders unfortunately. Those empty folders are a mix of folders with and without .nomedia if that helps.

**Comment by puregallery** [comment]
Did rescan at startup make them go away? Or are they visible all the time?

**Comment by Nostang3** [comment]
Visible all the time even with media scan or search for missing folders.

**Comment by puregallery** [comment]
Sigh...wonder why they are added in the first place. Can you take the latest build and clear the data for the app. I think the old build added some useless metadata. 
Sorry for the trouble man...you've been a great help frankly 😃

**Comment by Nostang3** [comment]
Definitely weird how it's holding on to folders that aren't even popular ones I use. Most are just one off folders that might have been used once. 

I cleared the data for both apps and I still see empty folders in the Beta build.

**Comment by puregallery** [comment]
Can you use file explorer to see if those folders have any content in it? 
Check for hidden files too. Fyi...files can be hidden using the .filename notion too.
I will look at the code to analyze why it would add an empty folder on first run. 
This is really weird. In my code, before I populate the views, I explicitly try to remove albums with no pictures in it. Can you try changing to 'tags' and switch back to 'albums' to see if it clears the empty ones.

**Comment by puregallery** [comment]
Also, in the first media scan when the app is installed, I only query the Android OS for the list of 'media' files it is holding references to. I wonder if the OS itself is holding on to ghost files that are deleted. The OS's media scan is not usually triggered until a restart of the device. If it is possible, can you try rebooting the device, and then clear the data for the debug version and try this again?

**Comment by Nostang3** [comment]
I went through a few of them and Root Explorer doesn't show any files in
it. Not even a .nomedia file. RE has show hidden files checked in it's
setitngs.

Switching to tags then back to Albums shows no albums at all. Not even the
camera folder. When I touched the screen they appeared including the empty
ones. I tried to do it again but then it started getting weird. The I was
in tags but it said albums at the top. I had to click back and forth
between them before the names righted themselves. Removing beta PG from
recents list and opening it again shows a blank screen missing albums.
Touching the screen brings them back.

**Comment by Nostang3** [comment]
I rebooted and then cleared the data for beta PG. After granting storage permission and letting it do a media scan the empty folders returned.

**Comment by puregallery** [comment]
>Switching to tags then back to Albums shows no albums at all. Not even the
camera folder. When I touched the screen they appeared including the empty
ones. I tried to do it again but then it started getting weird.The I was
in tags but it said albums at the top. I had to click back and forth
between them before the names righted themselves. Removing beta PG from
recents list and opening it again shows a blank screen missing albums.
Touching the screen brings them back.

Just found and fixed this issue...
For the sake of a smooth experience, the things i had to attempt were probably never heard of 😢  

Anyway, the empty folders is a little concerning...I'll look into that today.

**Comment by puregallery** [comment]
Can you try the latest build? Please clear the data of the app from settings and let it run.
The switching tabs has been fixed.
And am hoping the empty folder issue to be resolved too...I don't see any empty folders on my device. I am wondering what your configuration on these ghost folders are.

**Comment by Nostang3** [comment]
The app is force closing every time I open it after I granted it storage permission. 

Edit: This might help. I don't think there is any identifying information, if there is let me know so I can remove it. 
[logcat.txt](https://github.com/puregallery/Pure-Gallery-Support/files/2411010/logcat.txt)

**Comment by puregallery** [comment]
No identifying information is found...but the crash is weird. The app is failing to create SharedPreferences. To speed things up, I moved these steps into a background thread. I don't see why that would be a problem. Sigh...sorry man.

**Comment by Nostang3** [comment]
Don't worry about it. I used to test software for a living and I help a xposed module dev pretty often. You're app is what I need right now so anything I can do to help get it golden, I'm happy to help.

**Comment by puregallery** [comment]
Good to know...I will promise to deliver everything you ask for :) 
I don't see this happening on 3 of my devices, 2 on Oreo, 1 on Nougat. Is your device running low on space? I think that is the only time where creating the preferences will fail. Can you try rebooting the device and report back?

**Comment by Nostang3** [comment]
It better not be, my last phone was a 16gb and I was running out of space all the time. I made sure to buy this 120Gb Pixel XL so I didn't have to worry about that again. Lol.

Before reboot I had 35.72GB used out of 119GB according to the phone. After reboot I have 35.71GB used. 

Good news: The app will launch now. 
Bad news: The empty folders are still there. 
Good news: There are only a couple of them now. 
Bad news: It is not showing me any of my actual hidden ones until I did a media scan. 

Over all that's some progress. I double checked the two folders that are showing and only one of them has a file in it, and it's a .nomedia file.

**Comment by puregallery** [comment]
Lol...I don't know why the system failed to create preferences when there is so much space. It is the operating system's job and not the App's responsibility in any way.
The first media scan is not a 'full media scan'. It only asks the OS what files are visible and scans them. Invoking the 'full media scan' from settings is the only way to find hidden folders.

Anyway, thats a relief to know the hidden folders issue is reduced by some extent. I will look into why the folder with just the noMedia file shows up.

**Comment by Nostang3** [comment]
I uninstalled the previous version before installing the new debug. I figured that would be the same as clearing the storage. Maybe the system thought the new version was the old uninstalled version until reboot. 

Just to be clear. There is one empty folder/album with no files in it and one with just a .nomedia file. 

I checked dPB again and now it shows two empty folders with nothing in them. I double checked with a file explorer. I'll keep checking back to see if the folders keep changing.

**Comment by puregallery** [comment]
>There is one empty folder/album with no files in it and one with just a .nomedia file.

Got it, this was a good head start for me. I only understand why the .nomedia file's folder would show up. The other folder is still a mystery to me. I will just check the code over again.

**Comment by Nostang3** [comment]
If I use the Album options and delete an empty album, it removes it from dPG and doesn't show back up.

Also, I did a media scan and it crashed the app. I tried to recreate it for a matlog but i am not successful.

**Comment by puregallery** [comment]
I have Crashylitics enabled in the App...so, any crashes will be reported there. I will see the crash soon.

**Comment by Nostang3** [comment]
I hope they are automatic because the crashes today haven't given me the option to send error report.

**Comment by puregallery** [comment]
Yes, they are automatic...just saw the crash pop up there too. There is usually a delay withe these.

**Comment by puregallery** [comment]
Can you try the new build from the drive folder, clear the data and test this again?

**Comment by Nostang3** [comment]
I installed over the previous version, cleared all data, then opened it up. 

There is one empty folder showing up. 

Trying to move a file from one folder to another, after the move operation, it went back to the main album view then swapped the places of the folders, but it still showed the file in the folder like it hadn't been moved. Tried to move it again, it seems to complete the operation. Looking in a file explorer the folder is empty but the view doesn't reflect that. Searching for missing folders doesn't remove it nor does swipe down to refresh. A media scan and swipe down to refresh doesn't remove it either.

**Comment by puregallery** [comment]
Can you try switching to the nested view and report what happens...
I am close to zeroing on this stupid issue man...this bug tested my patience a lot 😢

**Comment by Nostang3** [comment]
In bPG, when I got to 'Nested Folders' it still shows the empty folder. Also, it shows another empty folder but this time it shows it has a picture in it and you can open the picture. I checked in a File Explorer and the directory is empty.

**Comment by puregallery** [comment]
Not the nested folders....while in the albums tab, open the options through the three dot menu and switch to nested.
Images are cached once loaded. I'm pretty sure the database wasn't cleaned up properly...am looking into why that would happen.

**Comment by Nostang3** [comment]
Ah, my bad. Switching to Nested View reaps the same results.

**Comment by puregallery** [comment]
Its gonna another week before I get this project back on track...sorry for the delay :(

**Comment by Nostang3** [comment]
Don't stress about it. PG still does what I need so no rush. I know how life can be sometimes.

**Comment by puregallery** [comment]
Please try out the new build and let me know if the empty folders issue is gone.

**Comment by Nostang3** [comment]
So I updated to the new build and the same issue is present. One empty album shows an album cover, another empty one doesn't show an album cover. And to update things, an album that I deleted since using dPG still shows up in it with an album cover. Tried running media scan but did nothing.

Tried clearing out the data for dPG. Now it shows 8 empty albums. The good news is that they aren't the same albums as before.

**Comment by puregallery** [comment]
Before this refactor, I perform a sanity check for empty folders right before displaying them...that includes updating the database as well, which consumes time. With this refactor, I was hoping things would automatically fall in place without the need for that sanity check. I might as well include that check for now, and optimize it later on.

**Comment by puregallery** [comment]
Check the new version now...
If this doesn't fix it. I will need help from you in debugging your database. I will give you steps later on...

EDIT: This version will show an empty state temporarily at startup...

**Comment by Nostang3** [comment]
Looks like we are going to have to debug my database. The empty folders are still there. Let me know what you need from me on that.

**Comment by puregallery** [comment]
Download the new build from drive...I have a few debug flags enabled on it. This will enable us to browse your database from a browser (PC or Mobile)
Make sure you are on WIFI...after you open the app, the app will display a port number in the notification bar...you need to enter this command on your phone to enable browsing your database
'adb forward tcp:8090 tcp:8090' . Substitute the port number if it is different that this.

After that, on a device connected to the same wifi, open this url -- http://localhost:8090/index.html

PG has 4 tables in total...we are interested in two of them right now...'Photo' and 'PhotoAlbum'.

Look thru the albums in the 'PhotoAlbum' table and copy the path of one of the folders. Go to the 'Photo' table and click on the filter icon next to that...select 'albumPath' property....with operator equals and paste the value in there. Let me know what you see there. If there are any images under that album, it means PG thinks the files still exist.

After you are done debugging, force stop the app from settings to stop the data browser service. The database can be accessible only to local devices(Mobile browser or devices on the same WIFI)

**Comment by Nostang3** [comment]
> After that, on a device connected to the same wifi, open this url -- http://localhost:8090/index.html

I think you mean
> After that, on a device connected to the same wifi, open this url -- http://**localIPAddress**:8090/index.html

For some reason I could only do 'contains' in the operator field. I couldn't even type in another value for it. I did find the PhotoAlbum path in Photo. The location for three of them says 'null', the 4th doesn't say anything for location.

![image](https://user-images.githubusercontent.com/25465114/46705992-281f3400-cc00-11e8-8edf-6229d1198c30.png)

**Comment by puregallery** [comment]
The location here means the gps location...that doesn't matter for us here.
Can you go to that folder and check if these files exist? Also, from the 'path' variable here...do they seem like media files? i.e jpg, png, mp4 etc

Yeah....contains is good enough for our testing

Just to clarify...these show up under your empty folder right?

**Comment by Nostang3** [comment]
Root Explorer says that nothing is in that particular folder. Not even a .nomedia file. 

That particular empty album lists .jpg files. But another empty album shows a .mp4 file. That's going to be the most common two files.

![image](https://user-images.githubusercontent.com/25465114/46707852-c2d04080-cc09-11e8-9a23-1a185d494d10.png)

**Comment by puregallery** [comment]
Can you try the build now? I think the new database library has some bugs...
I reverted temporarily to the old format in this build and want to check it this issue exists in it...please clear the data before installing.

**Comment by Nostang3** [comment]
Reverting to the old database fixed the empty folders issue. It now only shows populated albums.

**Comment by puregallery** [comment]
Shit man...I was trying to debug the other library so far then. This is both hilarious and sad.
I guess I will report the bug to them and continue with our old database. At least in my current implementation, things are happening a bit faster and not slowing the UI down.

Did you observe the slight delay initially when you launch the app? Is that delay bearable? Or should I do something about it? I'm thinking of displaying a small animation until the database fetch is complete...roughly .5 seconds on my device.

**Comment by Nostang3** [comment]
The first search for folders seemed to take a little longer and made me question it but I think that is to be expected on a initial scan. I haven't noticed anything that made me notice any lag or slow down as far as the UI goes in using since that scan.

**Comment by puregallery** [comment]
As soon as you open the app...there will be a small delay(about 0.5 - 0.8 seconds on my device with 14k pictures) until the images show up in the list. This of course varies based on the number of images you have on your device...
Either way, this approach sounds like the best plan for now...I'll look into switching to the other library once they fix their bugs...

Now I can actually concentrate on the functionality here... 🤕

**Comment by Nostang3** [comment]
Any delay opening the app seems okay for me right now. It's not as smooth as PG is, but that's something can smooth out over time. I think having a working database is more important currently. Remember, you've had the ability to see the app over time, so your judgement of it's speed is different than someone who will be a fresh user when you release the full version. 

The largest album I have is about 1600, and the max that will be on my device is only going to be around 1800 at any given time. That album grows so that number will change as time goes on.

**Comment by Nostang3** [comment]
I don't want to break your heart but I noticed a empty album in this version of dPG. SO the issue is in both databases.

**Comment by puregallery** [comment]
Its fine...no worries. But the number of empty folders seem to be less here.

Can you try the "Search for missing folders" from the option menu? I want to know if that will fix it.

EDIT: Also, what did the metadata on the album's card report? How many items does it think there are in it?

**Comment by Nostang3** [comment]
Actually, yeah, it did clear it from the view. I thought I tried that, but I guess I didn't. 

It only showed one item in the album.

**Comment by puregallery** [comment]
Ah, that's good to know. 
The full media scan also should be clearing 'gone' items, which it wasn't. Am fixing that up too...

**Comment by puregallery** [comment]
which version of the app are you using right now? 
I'm seeing some old versions pop up...wondering if that's you. Each version sort of has a time to live value...let me know if you want to revert to an old version.
I will be pushing a release out tomorrow though...all these issues are gone.

**Comment by Nostang3** [comment]
RC5 for both Debug and Stable.

**Comment by puregallery** [comment]
Oh, Ok. Among my current users, I thought you would be the only one with enough technical skills to save old versions and use them. 
The currently active build's number is 45...but I saw someone trying to use 29, 24, 41 in the past few weeks. Thought I'd help you if that were you.

**Comment by Nostang3** [comment]
Yeah, I not to try and use different versions while debugging or troubleshooting unless specified. I know that causes a lot of headaches on your when you're trying to figure things out when you think I have X version but using Y version. Since I'm helping you, I'm trying to be consistent as possible.

**Comment by puregallery** [comment]
Since I had to change the architecture of this app...can you test the latest RC release build from the drive folder? I want to perform a sanity check before pushing it to the masses. This is not a dev build/candidate. This will update the release version.

**Comment by Nostang3** [comment]
I'll make a back up on TB+ in case I need to revert. I'll install it and see if I have any issues.

**Comment by puregallery** [comment]
Sounds good...I will push this update to play store if you find everything good.

**Comment by Nostang3** [comment]
I am not sure how long you want me to test it, but after 24hrs, it hasn't given me any issues. I do feel like it's snappier. I also feel like it's finding folders easier once they have been added by a scan once.

**Comment by puregallery** [comment]
Oh, cool. I was actually hoping for a quick test...probably about an hour. I thought you wanted to be thorough and hence taking this time.
Anyway, thanks for the report. I will push the update to play store today.

This update has been the much needed performance boost for this app. The other database made it even faster, but it alone added 2MB to the apk file...not to mention a few bugs in it. I will definitely revisit that later on.

**Comment by Nostang3** [comment]
That's my bad then. I'm used to the other dev I help out where the tests are situational and I have to wait for the issue to happen like push notifications or something. I usually give it 24hrs before I reply. Feel free next time to say, "Hey give this a quick once over" or give me a time frame and how much you want to tested for cases like this. If I would have known you wanted a once over I would have replied last night.

**Comment by puregallery** [comment]
Yeah...no worries...am glad you had more time with it...and am not in any rush at the moment.

Good to hear the UI feels snappier to you.

**Comment by Nostang3** [comment]
And after I posted that I found a bug.  It seems that the album covers aren't showing. I noticed that PG thinks it set, but doesn't show the right picture. I tried removing and reselecting, tried a media scan, it continues to show the most recent photo of the album.

**Comment by puregallery** [comment]
ah, wish I saw this before pushing the release. Will push in the next one.

**Comment by Nostang3** [comment]
Looks like favorites are gone too.

**Comment by puregallery** [comment]
I can favorite items and see them in the app...did you mean the favorites from previous version are gone in this version?

**Comment by Nostang3** [comment]
Ah, I guess it wiped all my favorites when I upgraded to your RC version in the drive. It will show new favorites but not all my old ones. It didn't clear my settings so I figured it would have kept my favorites as well.

**Comment by puregallery** [comment]
yikes...didn't expect this. I will upgrade between the versions and check why this happened.

**Comment by Nostang3** [comment]
Also when copying/moving, PG shows a bunch of albums that aren't currently being used. Like they are in the database but don't have any files in them currently.

**Comment by puregallery** [comment]
They must have been the folders that are emptied somehow(Google upload etc)...is that the case?

EDIT: We can clear empty folders there...but I decided to give them as options.

**Comment by Nostang3** [comment]
It seems like any photo that has been scanned and viewed in PG. Folders that are synced, folders that I've manually moved/copied files from inside of PG. 

I personally liked it when they only showed the folders currently in use. I can see an issue that if you had a album with a hundred empty folders, it could be tedious to scroll through all of them to find that one folder that you need. Maybe a check box in settings for it?

**Comment by puregallery** [comment]
I'll add a toggle to display the hidden folders specifically then...

**Comment by Nostang3** [comment]
I had a thought, could you add a toggle to the move/copy dialog? It might be easier and quicker to be able to toggle while in the action than having to go back out to the menus or a 3rd party app. Just a thought this morning while copying.

**Comment by puregallery** [comment]
Sure. Will look into that. 
Can you do me a favor and close out the irrelevant bugs now? am trying to find things that needs attention in the issues list...and it feels a bit confusing at the moment.

**Comment by Nostang3** [comment]
I think I got all of them updated or closed.

**Comment by puregallery** [comment]
Cool...thanks. That will help me a lot.
 👍

**Comment by puregallery** [comment]
Sorry for the delay man...kind of getting hard to juggle between 3 jobs...I am planning on taking a week off from my full time job soon to finish all my projects...I will address all of our issues during that time. In the mean time, if you think any issue is a blocker for you, please let me know and I will push a fix for that soon. Until then, please keep your feedback coming.

**Comment by Nostang3** [comment]
No worries, do what you need to do. And no, I don't know of any deal blockers. The app seems to run smoothly most of the time. I use it everyday, multiple times a day, There are some quality of life issues that need to be addressed(issues already known) but nothing that keeps me from using the app.
