### ISSUE TITLE
Refreshing when in filtered tag view prevents clearing

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#89]
If you add new photos to a album then filter the view for those tags, one of the freshly tagged photos might not show up in the view, so you swipe to refresh the view to get the photo to appear. I then tried to clear the filter via the overlay button and the view didn't update. Going into the tag filter and clearing it there didn't clear it either. Going out of album and back in reset the view.

**Comment by puregallery** [comment]
@Nostang3 Finally scheduled my week off from 31 Dec-5th Jan.
I hope to wrap things up then.

**Comment by Nostang3** [comment]
@puregallery I'm off myself till the 3rd. Going to get my gaming on. But if you need some testing I'm happy to help, I got nothing going on for holidays.

**Comment by Nostang3** [comment]
I think this issue was fixed simply because new photos added appear without having to refresh.

I tagged a new photo and moved it to an album and filtered the view and the clear filter button was always visible when at the top of the album. Survived multiple refreshes.
