### ISSUE TITLE
Option for Last used/most frequent at top in the Modify Tag dialog when tagging. Last used or most frequent would help to speed up tagging by keeping the popular ones at the top instead of always have to scroll to the bottom for a frequently used one.

### ISSUE THREAD

**Issue by puregallery** [puregallery/Pure-Gallery-Support#9]

**Comment by puregallery** [comment]
Most used ones will be at the top always.

**Comment by Nostang3** [comment]
How does this work? No tags are at the top, so maybe figure it for most used going forward. When I tagged photos or videos and then go to another one, it doesn't have the recently used ones at the top. Is there a minimum number of uses before they become most used and are at the top?

**Comment by puregallery** [comment]
I am sorting this based on the number of photos with a particular tag...use the button on the screen to change the sort in there. To change it to add the most recently used tags, you might need to clear the data for the app on next upgrade. Are you fine with that?

**Comment by Nostang3** [comment]
There is no button on the Add Tags menu to sort the tags. 

As long as I'm not clearing tags on the photo, I don't mind clearing data for the app. Doesn't take much to set everything up again.

**Comment by puregallery** [comment]
This is weird...the button is indeed absent on the release build I published, but is present in my debug builds. Let me look into it.

**Comment by Nostang3** [comment]
This is now in the latest play store build, and it's very nice. I like the floating button you added. The only thing I would suggest is maybe the option to be able to toggle alphabetical to descending or ascending when you click on it.

**Comment by Nostang3** [comment]
The added option of sorting descending for alphabetical now works.
