### ISSUE TITLE
New 'Recent' Tag sort option is only working on fresh instance of app

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#90]
If I go into an album and change the sort to 'Frequent' or the ascending/descending 'Alphabetical' it works fine, but recent just shows ascending 'Alphabetical'. I have been recently tagging photos so I think the list should be populated and I thought at some point it worked....

Okay, so if I close the app out(back out and then swipe it from recents) while the recent tag option is set and go back into it, the recent option works. Once I switch it off to one of the other options, I can never get it back without closing the app.

Also, I think this option was a nice addition. Would work awesome if using the same tags for multiple photos.

**Comment by puregallery** [comment]
the 'Recent' options keeps track of when you have added tags through this application...essentially saving the time of applying.
Looks like these values are refreshed only after a 'pull down to refresh'...I will look into refreshing them every time the dialog is opened.
I don't think you need to kill and relaunch the app...just hit refresh(rescan folders) from the three dot menu..if you haven't disabled the swipe down to refresh, you can use that too

**Comment by Nostang3** [comment]
Okay, I'll keep that in mind the next time it happens to try that out.
