### ISSUE TITLE
File name on info bar missing file extention on certain file names

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#91]
Crap title.

So I have a few .jpgs that have the file name ending in say "(25).jpg". It seems that PG can't parse the rest of the file name ending in a special character? The name in the info bars will show the file name up until the first "(". 

The full file name is something like "Fall - Store 11252012 (25).jpg"

When viewing the info of the file via the info button, it will show the full correct name in both the 'Name' and 'Path' section.

**Comment by puregallery** [comment]
This might be a bug in the Database implementation...are you able to view the image fine?
If the name is being clipped at the database level, I don't expect the image to show up at all.
If the image shows up fine, then this is just a bug while displaying the text(title)

**Comment by Nostang3** [comment]
The images are displayed fine, just the name is truncated at the end. Missing I presume " (25).jpg" or "(25).jpg. I don't know if the space before the "(" is preserved or not.

**Comment by puregallery** [comment]
I cannot reproduce this. How many lines did the title display? I have a limit on the number of lines though - 2

**Comment by Nostang3** [comment]
Looks to be about 50 in the file name, 54 if you include the extension. The folder names are 8 characters or less.

**Comment by puregallery** [comment]
umm...I need the number of lines the title was displayed in.
Is it just a single line? or 2 lines?
Can't really calculate lines through characters...each device has a different dpi/resolution

**Comment by Nostang3** [comment]
My bad, I should English better. 

It uses 2 lines.

**Comment by puregallery** [comment]
No worries.
That explains it. It cut the name off since it is longer than 2 lines. 
I personally feel that the title should not take more than 2 lines...when it does, it will actually interfere with viewing the media itself. I am not against taking that check off...but do you see any point in having a long title? The full name can be viewed through the details too right.

**Comment by Nostang3** [comment]
I don't see the need to have the full name present, but you might consider abbreviated the name for long titles. Instead of 
"superlongnamethattakesupalotofspace.jpg" 
you could do 
"superlongnamethat...alotofspace.jpg" and remove enough spaces to have the name fit. 

I've seen this happen on progress bars. I guess the real question is do you preserve the ability to see the majority of the file name or see the file extension. If opening of this case is any indication, then people who can't see the file extension might be lead to believe that it's a bug instead of a limitation of the space available. And you're right, if they did wish to see the full name they can open the details dialog.

**Comment by puregallery** [comment]
Yeah...I was just going through the google photos app and they don't display the name at all.
You need to open the details to view any properties of a file.
For now, I will increase the number of max possible lines.

**Comment by puregallery** [comment]
I made the title 3 lines long...
