### ISSUE TITLE
RC9 Missing AND/OR toggle for tag filering

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#92]
I am not able to filter with multiple tags. For example, if I only want to see photos with cats that have dogs in it. Now it currently shows all photos with Cats and Dogs.

**Comment by Nostang3** [comment]
Is this in RC10? I don't see the toggle available anywhere.

**Comment by puregallery** [comment]
Ah, the toggle was pushed to the bottom when you have a lot of tags...will fix

**Comment by Nostang3** [comment]
The toggle is now back.
