### ISSUE TITLE
RC9: Was not able to change ascending/descending on alphabetical

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#93]
I was in album view and noticed that a newly tagged photo didn't have the tag icon on it. Swiped down to refresh and the icon appeared. I then went into add more tags to said photo but it would not allow me to change sort order of alphabetical. Tried swiping down to refresh again but that didn't help.

**Comment by Nostang3** [comment]
I am now able to change sort direction on alphabetical.

**Comment by Nostang3** [comment]
I saw that, and not I can't change order again. It looks like I can change sort order when applying tags, but not when I'm filtering tags. Was this ever a feature? I'm not sure if I ever could change sort direction on filtering.

**Comment by puregallery** [comment]
toggling asc/desc alphabetical in the album filter was not implemented...

**Comment by Nostang3** [comment]
Thanks for adding the toggling for the album filter. It's a small thing but it super helpful for me.
